{
  "formatVersion": "1.1",
  "component": {
    "url": "../../algoliasearch-client-kotlin/1.13.0-SNAPSHOT-zest/algoliasearch-client-kotlin-1.13.0-SNAPSHOT-zest.module",
    "group": "com.algolia",
    "module": "algoliasearch-client-kotlin",
    "version": "1.13.0-SNAPSHOT-zest",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "client-jvm-1.13.0-SNAPSHOT-zest.jar",
          "url": "algoliasearch-client-kotlin-jvm-1.13.0-SNAPSHOT-zest.jar",
          "size": 2723662,
          "sha512": "3be30ea617a97ac8311769804298e42b1d2f77d7b49cf530d9bcd2a63133175b163a693c3e2c8a7bdf62efbeae3afc09bba8829ab8f5338af479481f721884fd",
          "sha256": "81f79a359aafd88bd2468a33d40661c959922d884326aa11ec2f1dbe5d1257bd",
          "sha1": "711eaaecf6c9d2967f02a1596bb4564da1765cf9",
          "md5": "414d4d6ceb16295a385ec73a39c5142a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "client-jvm-1.13.0-SNAPSHOT-zest.jar",
          "url": "algoliasearch-client-kotlin-jvm-1.13.0-SNAPSHOT-zest.jar",
          "size": 2723662,
          "sha512": "3be30ea617a97ac8311769804298e42b1d2f77d7b49cf530d9bcd2a63133175b163a693c3e2c8a7bdf62efbeae3afc09bba8829ab8f5338af479481f721884fd",
          "sha256": "81f79a359aafd88bd2468a33d40661c959922d884326aa11ec2f1dbe5d1257bd",
          "sha1": "711eaaecf6c9d2967f02a1596bb4564da1765cf9",
          "md5": "414d4d6ceb16295a385ec73a39c5142a"
        }
      ]
    }
  ]
}
