fastlane_version "2.62.1"

default_platform :android

platform :android do
  
  desc "Runs all the tests"
  lane :test do
    gradle(task: "jvmTest")
  end

  desc "Deploy artifacts to Bintray"
  lane :deploy do
      gradle(task: "assemble bintrayUpload")
    end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
