{
  "formatVersion": "1.1",
  "component": {
    "url": "../../algoliasearch-client-kotlin/2.1.1-kmm-zest/algoliasearch-client-kotlin-2.1.1-kmm-zest.module",
    "group": "com.algolia",
    "module": "algoliasearch-client-kotlin",
    "version": "2.1.1-kmm-zest",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "client-jvm-2.1.1-kmm-zest.jar",
          "url": "algoliasearch-client-kotlin-jvm-2.1.1-kmm-zest.jar",
          "size": 2642115,
          "sha512": "404d476e74b5e33e3044b39967f186d5d9176814d8570e0e492bf95e76ff8c4f7d4c74c167aa6322ac235e66ee6af3203ed8a4034fe84eb5bc773c629f3ae2de",
          "sha256": "7ac687226d6aefe76149f182ed15fa0cc18e14ce418c7a4b2df29cef87f07373",
          "sha1": "547a06b108f92bb536e9cab7eb1c4df504e6131e",
          "md5": "e6ba3285331402196f53afbb4d8eaf1f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "client-jvm-2.1.1-kmm-zest.jar",
          "url": "algoliasearch-client-kotlin-jvm-2.1.1-kmm-zest.jar",
          "size": 2642115,
          "sha512": "404d476e74b5e33e3044b39967f186d5d9176814d8570e0e492bf95e76ff8c4f7d4c74c167aa6322ac235e66ee6af3203ed8a4034fe84eb5bc773c629f3ae2de",
          "sha256": "7ac687226d6aefe76149f182ed15fa0cc18e14ce418c7a4b2df29cef87f07373",
          "sha1": "547a06b108f92bb536e9cab7eb1c4df504e6131e",
          "md5": "e6ba3285331402196f53afbb4d8eaf1f"
        }
      ]
    }
  ]
}
