{
  "formatVersion": "1.1",
  "component": {
    "url": "../../algoliasearch-client-kotlin/1.13.0-SNAPSHOT-zest/algoliasearch-client-kotlin-1.13.0-SNAPSHOT-zest.module",
    "group": "com.algolia",
    "module": "algoliasearch-client-kotlin",
    "version": "1.13.0-SNAPSHOT-zest",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-ios",
          "version": {
            "requires": "1.6.5"
          }
        }
      ],
      "files": [
        {
          "name": "client.klib",
          "url": "algoliasearch-client-kotlin-iosarm64-1.13.0-SNAPSHOT-zest.klib",
          "size": 1488801,
          "sha512": "7e54903c9add3efefb1ecfc008be2a28ee723689566ca87912492d03802282a876020db96707ebe3e83a4cc2b75488fa1f93c530cba1b3227653eeb7fbfb1a1b",
          "sha256": "7b45507a5fc7adedd2f45ba515054e4552fd0725b17c2d2d8282c8d702281045",
          "sha1": "faa5be4603198485aa20f6b60bafa90bab20a7ba",
          "md5": "8e644ef3fd2e8abab26ac5af3c0f62b3"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-ios",
          "version": {
            "requires": "1.6.5"
          }
        }
      ],
      "files": [
        {
          "name": "client-iosarm64-1.13.0-SNAPSHOT-zest-metadata.jar",
          "url": "algoliasearch-client-kotlin-iosarm64-1.13.0-SNAPSHOT-zest-metadata.jar",
          "size": 12870,
          "sha512": "9b966684fafc854b86dfaa3648f44e0ab54b0a299b28635fd1cfe985c146b8b67daa070922a3ac657e1baeb9f6cf56a71382952dbc1a843f4c88f33ea078172f",
          "sha256": "bac778c29a196ca83bae46a85f85a662d4d1f949c97cbe1c8ef4012f92bd9c13",
          "sha1": "c174ed77d8c6754f2b39ba540e406ffbaa4ff122",
          "md5": "7140f70f7032546b85e3ba7efc53a9c7"
        }
      ]
    }
  ]
}
